import type { FoodItem } from "@/hooks/useCalorieCalculator";

// FoodItem tipini mealTypes ve category ile genişletiyoruz
export interface ExtendedFoodItem extends FoodItem {
  mealTypes: string[];
  category: string;
}

export const MOCK_FOODS: ExtendedFoodItem[] = [
  {
    id: "chicken-breast",
    name: "Tavuk Göğsü",
    brand: "Taze",
    caloriesPer100g: 165,
    proteinPer100g: 31,
    carbsPer100g: 0,
    fatPer100g: 3.6,
    fiberPer100g: 0,
    mealTypes: ["lunch", "dinner"],
    category: "chicken",
  },
  {
    id: "cooked-rice",
    name: "Pirinç (Pişmiş)",
    caloriesPer100g: 130,
    proteinPer100g: 2.7,
    carbsPer100g: 28,
    fatPer100g: 0.3,
    fiberPer100g: 0.4,
    mealTypes: ["lunch", "dinner"],
    category: "vegan",
  },
  {
    id: "oatmeal",
    name: "Yulaf Ezmesi",
    brand: "Doğal",
    caloriesPer100g: 389,
    proteinPer100g: 17,
    carbsPer100g: 66,
    fatPer100g: 7,
    fiberPer100g: 10.6,
    mealTypes: ["breakfast", "snack"],
    category: "vegan",
  },
  {
    id: "whole-egg",
    name: "Yumurta (Haşlanmış)",
    caloriesPer100g: 155,
    proteinPer100g: 13,
    carbsPer100g: 1.1,
    fatPer100g: 11,
    fiberPer100g: 0,
    mealTypes: ["breakfast", "snack"],
    category: "dairy",
  },
  {
    id: "salmon",
    name: "Somon Fileto",
    caloriesPer100g: 208,
    proteinPer100g: 20,
    carbsPer100g: 0,
    fatPer100g: 13,
    fiberPer100g: 0,
    mealTypes: ["lunch", "dinner"],
    category: "fish",
  },
  {
    id: "whole-wheat-bread",
    name: "Tam Buğday Ekmeği",
    caloriesPer100g: 247,
    proteinPer100g: 13,
    carbsPer100g: 41,
    fatPer100g: 4.2,
    fiberPer100g: 6.8,
    mealTypes: ["breakfast", "snack"],
    category: "pastry",
  },
  {
    id: "lentil",
    name: "Mercimek (Pişmiş)",
    caloriesPer100g: 116,
    proteinPer100g: 9,
    carbsPer100g: 20,
    fatPer100g: 0.4,
    fiberPer100g: 7.9,
    mealTypes: ["lunch", "dinner"],
    category: "legume",
  },
  {
    id: "beef-mince",
    name: "Kıyma (Yağsız)",
    caloriesPer100g: 215,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 12,
    fiberPer100g: 0,
    mealTypes: ["lunch", "dinner"],
    category: "meat",
  },
  {
    id: "greek-yogurt",
    name: "Yunan Yoğurdu",
    brand: "%0 Yağlı",
    caloriesPer100g: 59,
    proteinPer100g: 10,
    carbsPer100g: 3.6,
    fatPer100g: 0.4,
    fiberPer100g: 0,
    mealTypes: ["breakfast", "snack"],
    category: "dairy",
  },
  {
    id: "avocado",
    name: "Avokado",
    caloriesPer100g: 160,
    proteinPer100g: 2,
    carbsPer100g: 9,
    fatPer100g: 15,
    fiberPer100g: 7,
    mealTypes: ["breakfast", "snack", "lunch"],
    category: "vegan",
  },
  {
    id: "banana",
    name: "Muz",
    caloriesPer100g: 89,
    proteinPer100g: 1.1,
    carbsPer100g: 23,
    fatPer100g: 0.3,
    fiberPer100g: 2.6,
    mealTypes: ["breakfast", "snack"],
    category: "vegan",
  },
  {
    id: "tuna-can",
    name: "Konserve Ton Balığı",
    brand: "Suda",
    caloriesPer100g: 116,
    proteinPer100g: 26,
    carbsPer100g: 0,
    fatPer100g: 1,
    fiberPer100g: 0,
    mealTypes: ["lunch", "snack"],
    category: "fish",
  },
];
